AllCops:
  Excludes:
    - vendor/**

AlignParameters:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
BlockNesting:
  Enabled: false # @todo enable this
MethodLength:
  Max: 30

# Disabled to allow spacing of variables for readability
Style/SingleSpaceBeforeFirstArg:
  Enabled: false
